model:
  #   (type: str | None, default: null)
  encoder_ckpt_path: # PROVIDE
  #   (type: bool, default: False)
  freeze_encoder: true
  #   (type: ClassificationMode, default: LINEAR)
  classification_head_type: LINEAR

optim: optim/classification_optim_frozen.yaml

trainer:
  enable_checkpointing: false
  callbacks: null

data:
  init_args:
    deterministic_val_data: false